# Generated by Django 5.1.5 on 2025-01-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('description', models.TextField()),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='plantation.plantation')),
            ],
        ),
    ]
