# Generated by Django 5.1.5 on 2025-01-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0004_plantation_created_at_plantation_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plantation_credits', models.PositiveIntegerField(default=0)),
                ('employee_credits', models.PositiveIntegerField(default=0)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
