# Generated by Django 5.1.5 on 2025-01-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='plantation.corporate'),
        ),
    ]
