# Generated by Django 5.1.5 on 2025-02-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0008_visitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
