# Generated by Django 5.1.5 on 2025-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0009_visitrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantation',
            name='state',
            field=models.CharField(blank=True, choices=[('State1', 'State 1'), ('State2', 'State 2')], max_length=50, null=True),
        ),
    ]
