# Generated by Django 5.1.5 on 2025-03-24 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0011_timeline_activity_image_timeline_activity_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Comment'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
