# Generated by Django 5.1.5 on 2025-03-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0012_visitrequest_admin_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='status_updated_by',
        ),
    ]
