# Generated by Django 5.2 on 2025-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0013_remove_visitrequest_status_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='gifted_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who gifted this plantation (optional)', max_length=255, null=True),
        ),
    ]
